services:
  - type: web
    name: stock-trading-sim
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app
  - type: worker
    name: celery-worker
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: celery -A celery_worker.celery worker --loglevel=info
