services:
  - name: stock-trading-app
    type: web
    runtime: python
    region: oregon  # Change based on your preferred region
    plan: free  # Upgrade to 'starter' for better performance
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT src.app:app
    envVars:
      - key: CACHE_REDIS_URL
        fromService: redis-instance
      - key: CELERY_BROKER_URL
        fromService: redis-instance
      - key: CELERY_RESULT_BACKEND
        fromService: redis-instance
      - key: PORT
        value: 10000  # Default Flask port

  - name: celery-worker
    type: worker
    runtime: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: celery -A src.app.celery worker --loglevel=info
    envVars:
      - key: CELERY_BROKER_URL
        fromService: redis-instance
      - key: CELERY_RESULT_BACKEND
        fromService: redis-instance

  - name: redis-instance
    type: redis
    region: oregon
    plan: free
